apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ulimit-fixer
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: example.com/lock
        effect: NoExecute
